[package]
name = "main"
version = "0.1.0"
authors = ["toyama1710 <toyama@toyama1710.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
